### PR TITLE
Fix `Call to a member function getSettings() on null`

### PR DESCRIPTION
**Pull request by reganlawton**
Fixes issue #11 with `Call to a member function getSettings() on null` bug, that can sometimes be triggered.

**Recommend additional testing before accepting this PR, as I'm the single tester so far**

### CODE REVIEW

**Comment by bertoost** [comment]
Thanks @reganlawton ! I will merge this a.s.a.p.

**Comment by reganlawton** [comment]
@bertoost any moment on this?

**Comment by bertoost** [comment]
I will continue with this a.s.a.p. also need to update the editor itself, but so busy with many other things. Hopefully I can get this merged in the next few days.

**Comment by reganlawton** [comment]
Awesome 👍

**Comment by jlamb1** [comment]
any update on merging this? Currently i'm running my own forked version of Froala, without it either my CMS will break or i need to sacrifice several plugins. Thanks also to @reganlawton !

**Comment by bertoost** [comment]
Don't push that much. My last comment was from 2 days ago. I'm very busy at the moment and did not have the time yet to update the editor. But it will happen soon

**Comment by reganlawton** [comment]
@bertoost I can relate to this so much 🙌 No issues on the merge front just following up due to composer updates being slow when using a repo override. Im sure @jlamb1 is the same.

Also @jlamb1 no issues I'd like to say I did it for the community but I had a personal need haha.

**Comment by bertoost** [comment]
Again. Thanks for the help. It's appreciated. As you can see, I have merged it.

Found some other issues as well, which I have to investigate before releasing, but it will happen today :)

**Comment by reganlawton** [comment]
Awesome I’ll get  it merged in after the long weekend. Thanks again 🙏

**Comment by bertoost** [comment]
Seems not to be an issue. Heading to release v2.9.4 ;-)

**Pull request merged**
